import type { GiftProduct } from '@/types/gifts'

export const GIFT_CATEGORIES = [
  { value: 'all',        label: 'All Gifts',      emoji: '🎁' },
  { value: 'soft-toys',  label: 'Soft Toys',      emoji: '🧸' },
  { value: 'home-decor', label: 'Home Decor',     emoji: '🏡' },
  { value: 'perfumes',   label: 'Perfumes',        emoji: '🌸' },
  { value: 'candles',    label: 'Candles',         emoji: '🕯️' },
  { value: 'jewellery',  label: 'Jewellery',       emoji: '💎' },
  { value: 'chocolates', label: 'Chocolates',      emoji: '🍫' },
  { value: 'skincare',   label: 'Skincare',        emoji: '✨' },
  { value: 'plants',     label: 'Plants',          emoji: '🌿' },
  { value: 'books',      label: 'Books',           emoji: '📖' },
  { value: 'custom',     label: 'Customised',      emoji: '🎨' },
]

export const GIFTS: GiftProduct[] = [
  // ── SOFT TOYS ──
  {
    id: 'g001',
    name: 'Giant Memory Bear',
    tagline: 'Soft, warm, and yours to keep forever',
    description: 'A premium plush bear, 45cm tall, crafted from ultra-soft hypoallergenic velvet. Each bear comes with a hand-embroidered name tag and a tiny heart-shaped pocket where you can slip a note.',
    category: 'soft-toys',
    price: 189900,
    priceDisplay: '₹1,899',
    images: [
      'https://images.unsplash.com/photo-1559454403-b8fb88521f11?w=600&q=80&fit=crop',
      'https://images.unsplash.com/photo-1577730249840-4fc2f0bae0e4?w=600&q=80&fit=crop',
    ],
    badge: 'Bestseller',
    tags: ['birthday', 'romantic', 'kids', 'friendship'],
    inStock: true,
    rating: 4.8,
    reviewCount: 247,
    occasions: ['birthday', 'romantic', 'friendship'],
    deliveryDays: 3,
    storyBundle: true,
    bundleDiscount: 15,
  },
  {
    id: 'g002',
    name: 'Elephant Cuddle Plush',
    tagline: 'For the person who needs a hug you can\'t give in person',
    description: 'A 38cm hand-stitched elephant plush in ivory and blush. Memory foam fill. Comes in a kraft gift box with a small handwritten-style tag you can personalise.',
    category: 'soft-toys',
    price: 149900,
    priceDisplay: '₹1,499',
    images: [
      'https://images.unsplash.com/photo-1596460107916-430662021049?w=600&q=80&fit=crop',
    ],
    tags: ['birthday', 'baby', 'friendship'],
    inStock: true,
    rating: 4.6,
    reviewCount: 118,
    occasions: ['birthday', 'baby shower', 'friendship'],
    deliveryDays: 3,
    storyBundle: true,
    bundleDiscount: 10,
  },

  // ── HOME DECOR ──
  {
    id: 'g003',
    name: 'Personalised Star Map Print',
    tagline: 'The sky exactly as it looked on the night that changed everything',
    description: 'A museum-quality giclée print showing the exact position of stars over any location on any date you choose. 30cm × 40cm, printed on 300gsm archival paper. Frame-ready.',
    category: 'home-decor',
    price: 249900,
    priceDisplay: '₹2,499',
    images: [
      'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&q=80&fit=crop',
    ],
    badge: 'Customised',
    tags: ['romantic', 'anniversary', 'birthday', 'luxury'],
    inStock: true,
    rating: 4.9,
    reviewCount: 312,
    occasions: ['anniversary', 'birthday', 'romantic', 'wedding'],
    deliveryDays: 5,
    storyBundle: true,
    bundleDiscount: 20,
  },
  {
    id: 'g004',
    name: 'Dried Flower Terrarium',
    tagline: 'A little garden that never wilts',
    description: 'Hand-assembled glass terrarium filled with preserved roses, pampas grass, eucalyptus, and dried wildflowers. Each one is unique. Approx 15cm × 20cm. No maintenance required.',
    category: 'home-decor',
    price: 189900,
    priceDisplay: '₹1,899',
    images: [
      'https://images.unsplash.com/photo-1487530811015-780038bb7b4f?w=600&q=80&fit=crop',
    ],
    badge: 'New',
    tags: ['romantic', 'birthday', 'home', 'elegant'],
    inStock: true,
    rating: 4.7,
    reviewCount: 89,
    occasions: ['birthday', 'anniversary', 'housewarming'],
    deliveryDays: 4,
    storyBundle: true,
    bundleDiscount: 10,
  },
  {
    id: 'g005',
    name: 'Woven Macramé Wall Hanging',
    tagline: 'Handmade, one at a time, for wherever feels like home',
    description: 'A 60cm hand-knotted macramé wall piece in natural cotton rope with driftwood dowel. Boho-luxe aesthetic. Each piece is made by artisans in Rajasthan.',
    category: 'home-decor',
    price: 159900,
    priceDisplay: '₹1,599',
    images: [
      'https://images.unsplash.com/photo-1522444816890-4b551f5c3503?w=600&q=80&fit=crop',
    ],
    tags: ['housewarming', 'birthday', 'home'],
    inStock: true,
    rating: 4.5,
    reviewCount: 64,
    occasions: ['birthday', 'housewarming'],
    deliveryDays: 5,
  },

  // ── PERFUMES ──
  {
    id: 'g006',
    name: 'Rose & Oud Eau de Parfum',
    tagline: 'The scent of someone you\'d rather be next to',
    description: 'A warm, deeply romantic 50ml EDP. Top notes of Bulgarian rose and bergamot, heart of saffron oud, base of sandalwood and amber. Long-lasting, 8–12 hours. Comes in a magnetic gift box.',
    category: 'perfumes',
    price: 349900,
    priceDisplay: '₹3,499',
    images: [
      'https://images.unsplash.com/photo-1541643600914-78b084683702?w=600&q=80&fit=crop',
    ],
    badge: 'Luxury',
    tags: ['romantic', 'anniversary', 'birthday', 'luxury'],
    inStock: true,
    rating: 4.9,
    reviewCount: 156,
    occasions: ['anniversary', 'birthday', 'romantic', 'celebration'],
    deliveryDays: 3,
    storyBundle: true,
    bundleDiscount: 15,
  },
  {
    id: 'g007',
    name: 'Jasmine Nights Rollerball Set',
    tagline: 'Three moods. All yours.',
    description: 'A curated set of three 10ml rollerball perfumes — Jasmine Night, Warm Vetiver, and Fresh Citrus Bloom. Perfect to try before you commit. Presented in a hand-folded origami box.',
    category: 'perfumes',
    price: 199900,
    priceDisplay: '₹1,999',
    images: [
      'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=600&q=80&fit=crop',
    ],
    tags: ['birthday', 'friendship', 'self-care'],
    inStock: true,
    rating: 4.7,
    reviewCount: 203,
    occasions: ['birthday', 'friendship', 'celebration'],
    deliveryDays: 3,
    storyBundle: true,
    bundleDiscount: 10,
  },

  // ── CANDLES ──
  {
    id: 'g008',
    name: 'Memory Lane Soy Candle',
    tagline: 'Light it when you need to feel like they\'re nearby',
    description: 'A 220g hand-poured soy wax candle with a 45-hour burn time. Scented with sandalwood, vanilla, and a touch of rose. Comes in a matte black glass jar. You can add a custom label message.',
    category: 'candles',
    price: 129900,
    priceDisplay: '₹1,299',
    images: [
      'https://images.unsplash.com/photo-1608181831718-c9a52e93b59a?w=600&q=80&fit=crop',
    ],
    badge: 'Customised',
    tags: ['romantic', 'birthday', 'memorial', 'self-care'],
    inStock: true,
    rating: 4.8,
    reviewCount: 178,
    occasions: ['birthday', 'anniversary', 'memorial', 'self-care'],
    deliveryDays: 3,
    storyBundle: true,
    bundleDiscount: 10,
  },
  {
    id: 'g009',
    name: 'Bloom & Citrus Candle Trio',
    tagline: 'One for morning. One for evening. One for when you can\'t sleep.',
    description: 'Three 100g soy candles: Bergamot & Lemon (morning), Neroli & Jasmine (evening), and Lavender & Chamomile (night). Hand-poured in Goa. 30-hour burn each.',
    category: 'candles',
    price: 249900,
    priceDisplay: '₹2,499',
    images: [
      'https://images.unsplash.com/photo-1574706636034-a35e1bb8d5d0?w=600&q=80&fit=crop',
    ],
    tags: ['birthday', 'self-care', 'home', 'friendship'],
    inStock: true,
    rating: 4.6,
    reviewCount: 94,
    occasions: ['birthday', 'celebration', 'self-care'],
    deliveryDays: 3,
  },

  // ── JEWELLERY ──
  {
    id: 'g010',
    name: 'Engraved Coordinates Bracelet',
    tagline: 'The exact spot where it all began',
    description: 'Sterling silver cuff bracelet engraved with latitude/longitude coordinates of any place you choose. 18cm adjustable. Comes in a velvet pouch with a meaning card.',
    category: 'jewellery',
    price: 299900,
    priceDisplay: '₹2,999',
    images: [
      'https://images.unsplash.com/photo-1573408301185-9519f94816b5?w=600&q=80&fit=crop',
    ],
    badge: 'Customised',
    tags: ['romantic', 'anniversary', 'birthday', 'luxury'],
    inStock: true,
    rating: 4.9,
    reviewCount: 267,
    occasions: ['anniversary', 'birthday', 'romantic'],
    deliveryDays: 7,
    storyBundle: true,
    bundleDiscount: 20,
  },
  {
    id: 'g011',
    name: 'Pressed Flower Resin Necklace',
    tagline: 'A little garden to wear around your neck',
    description: 'Real dried flowers suspended in hand-poured resin, set in an 18K gold-filled pendant. 45cm chain included. Each piece is unique — no two are identical.',
    category: 'jewellery',
    price: 199900,
    priceDisplay: '₹1,999',
    images: [
      'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=600&q=80&fit=crop',
    ],
    tags: ['birthday', 'romantic', 'friendship', 'nature'],
    inStock: true,
    rating: 4.7,
    reviewCount: 142,
    occasions: ['birthday', 'anniversary', 'friendship'],
    deliveryDays: 5,
  },

  // ── CHOCOLATES ──
  {
    id: 'g012',
    name: 'Artisan Truffle Box',
    tagline: 'Because some feelings are best communicated in chocolate',
    description: 'A curated box of 12 handmade Belgian chocolate truffles. Flavours include dark espresso, rose cardamom, salted caramel, and white hazelnut. Presented in a keepsake wooden box.',
    category: 'chocolates',
    price: 179900,
    priceDisplay: '₹1,799',
    images: [
      'https://images.unsplash.com/photo-1549007994-cb92caebd54b?w=600&q=80&fit=crop',
    ],
    badge: 'Bestseller',
    tags: ['birthday', 'romantic', 'celebration', 'luxury'],
    inStock: true,
    rating: 4.8,
    reviewCount: 389,
    occasions: ['birthday', 'anniversary', 'celebration', 'romantic'],
    deliveryDays: 2,
    storyBundle: true,
    bundleDiscount: 10,
  },
  {
    id: 'g013',
    name: 'Single-Origin Dark Chocolate Bar',
    tagline: '72% Coorg cocoa. Nothing added. Nothing taken away.',
    description: 'A 150g single-origin dark chocolate bar sourced from a family farm in Coorg. Stone-ground, no additives. Comes wrapped in handmade paper with a wax seal.',
    category: 'chocolates',
    price: 89900,
    priceDisplay: '₹899',
    images: [
      'https://images.unsplash.com/photo-1481391319762-47dff72954d9?w=600&q=80&fit=crop',
    ],
    tags: ['birthday', 'self-care', 'foodie'],
    inStock: true,
    rating: 4.6,
    reviewCount: 156,
    occasions: ['birthday', 'celebration', 'self-care'],
    deliveryDays: 2,
  },

  // ── SKINCARE ──
  {
    id: 'g014',
    name: 'Rose Ritual Gift Set',
    tagline: 'For the skin they\'re already in',
    description: 'A four-piece skincare set: rose face mist (150ml), vitamin C serum (30ml), overnight rose mask (50g), and lip treatment balm. All clean ingredients, no parabens. Comes in a reusable jute tote.',
    category: 'skincare',
    price: 299900,
    priceDisplay: '₹2,999',
    images: [
      'https://images.unsplash.com/photo-1596755389378-c31d21fd1273?w=600&q=80&fit=crop',
    ],
    badge: 'Premium',
    tags: ['birthday', 'self-care', 'friendship', 'luxury'],
    inStock: true,
    rating: 4.8,
    reviewCount: 201,
    occasions: ['birthday', 'friendship', 'self-care', 'celebration'],
    deliveryDays: 3,
    storyBundle: true,
    bundleDiscount: 15,
  },
  {
    id: 'g015',
    name: 'Ayurvedic Self-Care Hamper',
    tagline: 'Old wisdom. New rituals.',
    description: 'Seven products rooted in Ayurvedic traditions: kumkumadi oil, ashwagandha body butter, chandan face pack, neem toner, rose gulkand lip balm, amla hair serum, and sandalwood bath salts.',
    category: 'skincare',
    price: 349900,
    priceDisplay: '₹3,499',
    images: [
      'https://images.unsplash.com/photo-1619451334792-150fd785ee74?w=600&q=80&fit=crop',
    ],
    tags: ['birthday', 'self-care', 'wellness', 'luxury'],
    inStock: true,
    rating: 4.7,
    reviewCount: 167,
    occasions: ['birthday', 'self-care', 'wellness'],
    deliveryDays: 4,
  },

  // ── PLANTS ──
  {
    id: 'g016',
    name: 'Potted Money Plant in Ceramic Pot',
    tagline: 'Something living. Something growing.',
    description: 'A healthy money plant in a hand-painted ceramic pot (15cm). Comes with a care guide card and a 3-month growth guarantee. Low maintenance, air-purifying, and beautiful.',
    category: 'plants',
    price: 69900,
    priceDisplay: '₹699',
    images: [
      'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=600&q=80&fit=crop',
    ],
    tags: ['housewarming', 'birthday', 'home', 'wellness'],
    inStock: true,
    rating: 4.5,
    reviewCount: 88,
    occasions: ['housewarming', 'birthday', 'celebration'],
    deliveryDays: 2,
  },
  {
    id: 'g017',
    name: 'Succulent Garden Trio',
    tagline: 'Three little lives that are very hard to kill',
    description: 'Three hand-selected succulents in matching terracotta pots, arranged on a small driftwood tray. Includes a care booklet and a bag of premium cactus soil.',
    category: 'plants',
    price: 129900,
    priceDisplay: '₹1,299',
    images: [
      'https://images.unsplash.com/photo-1459156212016-c812468e2115?w=600&q=80&fit=crop',
    ],
    tags: ['housewarming', 'birthday', 'home', 'friendship'],
    inStock: true,
    rating: 4.6,
    reviewCount: 113,
    occasions: ['housewarming', 'birthday', 'friendship'],
    deliveryDays: 2,
  },

  // ── BOOKS ──
  {
    id: 'g018',
    name: 'The Poetry of Staying — Curated Anthology',
    tagline: 'For people who feel things deeply',
    description: 'A 220-page hardback anthology of 50 poems about love, longing, belonging, and return. Curated by our editorial team. Printed on cream-tinted paper with hand-stitched binding and gold foil title.',
    category: 'books',
    price: 159900,
    priceDisplay: '₹1,599',
    images: [
      'https://images.unsplash.com/photo-1481277542470-605612bd2d61?w=600&q=80&fit=crop',
    ],
    badge: 'Exclusive',
    tags: ['birthday', 'romantic', 'literary', 'friendship'],
    inStock: true,
    rating: 4.9,
    reviewCount: 92,
    occasions: ['birthday', 'anniversary', 'romantic', 'friendship'],
    deliveryDays: 4,
    storyBundle: true,
    bundleDiscount: 10,
  },

  // ── CUSTOM ──
  {
    id: 'g019',
    name: 'Custom Illustrated Portrait',
    tagline: 'A painting of the two of you. Or the one of you. Or all of you.',
    description: 'A professional digital illustration in watercolour style, printed on 300gsm art paper (A4 or A3). Send us a photo, choose a background colour, and receive your framed artwork within 7 days.',
    category: 'custom',
    price: 499900,
    priceDisplay: '₹4,999',
    images: [
      'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=600&q=80&fit=crop',
    ],
    badge: 'Made For You',
    tags: ['anniversary', 'birthday', 'wedding', 'luxury'],
    inStock: true,
    rating: 4.9,
    reviewCount: 78,
    occasions: ['anniversary', 'birthday', 'wedding', 'romantic'],
    deliveryDays: 10,
    storyBundle: true,
    bundleDiscount: 20,
  },
  {
    id: 'g020',
    name: 'Personalised Recipe Book',
    tagline: 'Every dish you make for them, bound and beautiful',
    description: 'A hardback blank recipe book with custom name and dedication page printed inside the cover. Lay-flat binding, 120 ruled recipe pages, space for photos. 25cm × 20cm.',
    category: 'custom',
    price: 199900,
    priceDisplay: '₹1,999',
    images: [
      'https://images.unsplash.com/photo-1466637574441-749b8f19452f?w=600&q=80&fit=crop',
    ],
    tags: ['birthday', 'wedding', 'home', 'foodie'],
    inStock: true,
    rating: 4.7,
    reviewCount: 134,
    occasions: ['birthday', 'wedding', 'anniversary'],
    deliveryDays: 7,
  },
]

export function getGiftById(id: string): GiftProduct | undefined {
  return GIFTS.find(g => g.id === id)
}

export function getGiftsByCategory(cat: string): GiftProduct[] {
  if (cat === 'all') return GIFTS
  return GIFTS.filter(g => g.category === cat)
}

export function getGiftsByOccasion(occasion: string): GiftProduct[] {
  return GIFTS.filter(g => g.occasions.includes(occasion))
}

export function getRelatedGifts(gift: GiftProduct, limit = 4): GiftProduct[] {
  return GIFTS
    .filter(g => g.id !== gift.id && (g.category === gift.category || g.tags.some(t => gift.tags.includes(t))))
    .slice(0, limit)
}

export function formatPrice(paise: number): string {
  return `₹${(paise / 100).toLocaleString('en-IN')}`
}
